package com.bettersms.badippe.entites;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by badache on 20/10/15.
 */
public class Message {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    private int Id;
    @DatabaseField(canBeNull = false)
    private String sendingTime;
    @DatabaseField(canBeNull = false)
    private String sendingTo;
    @DatabaseField(canBeNull = false)
    private String messageContent;


    Message() {
        // needed by ormlite
    }

    public Message(String messageContent, String sendingTo, String sendingTime) {
        this.messageContent = messageContent;
        this.sendingTo = sendingTo;
        this.sendingTime = sendingTime;
    }

    public int getId() {
        return Id;
    }

    public String getSendingTime() {
        return sendingTime;
    }

    public String getSendingTo() {
        return sendingTo;
    }

    public String getMessageContent() {
        return messageContent;
    }

    @Override
    public String toString() {
        return "Message{" +
                "Id=" + Id +
                ", sendingTime='" + sendingTime + '\'' +
                ", sendingTo='" + sendingTo + '\'' +
                ", messageContent='" + messageContent + '\'' +
                '}';
    }
}
